version: '3.5'

services:

  # PostreSQL
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: storage
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - beans-network

  # MongoDB
  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: storage
    networks:
      - beans-network

  # Redis cache
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - 6379:6379
    command: '--requirepass root'
    networks:
      - beans-network

  # Liquibase
  liquibase:
    image: liquibase/liquibase:4.9.1
    container_name: liquibase
    depends_on:
      - postgres
    volumes:
      - ./src/main/resources/db/changeLog:/liquibase/changelog
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/storage
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_CHANGELOG=/liquibase/changelog/changeLog.xml
      - CLASSPATH=/liquibase/changelog
    command:
      - --changeLogFile=changeLog.xml
      - --url=jdbc:postgresql://postgres:5432/storage
      - --username=root
      - --password=root
      - update
    networks:
      - beans-network

  # Spring boot application
  beans:
    container_name: beans
    depends_on:
      - postgres
      - redis
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - beans-network
    restart: on-failure

# Docker containers network (name attribute is needed!)
networks:
  beans-network:
    name: beans-network
    driver: bridge
